# PostgreSQL Database Settings
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0

# Redis Queue Settings
REDIS_HOST=redis
REDIS_PORT=6379

# Sandbox Executions Settings
# Give adequate runtimes for larger C++ compilations
CPU_TIME_LIMIT=5.0
CPU_EXTRA_TIME_LIMIT=1.0
WALL_TIME_LIMIT=10.0
MEMORY_LIMIT=256000
STACK_LIMIT=64000
MAX_PROCESSES_AND_OR_THREADS=60
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=true
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=true
MAX_FILE_SIZE=1024
ALLOW_CUSTOM_SANDBOX_PARAMETERS=false
