version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always

  db:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0

  server:
    image: judge0/judge0:latest
    container_name: judge0
    restart: always
    ports:
      - "2358:2358"
    privileged: true
    volumes:
      - ./judge0.conf:/judge0.conf
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    depends_on:
      - redis
      - db

  workers:
    image: judge0/judge0:latest
    container_name: judge0-worker
    command: ["./scripts/workers"]
    restart: always
    privileged: true
    volumes:
      - ./judge0.conf:/judge0.conf
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    depends_on:
      - redis
      - db

  backend:
    build: .
    container_name: code-judge-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - JUDGE0_URL=http://judge0:2358
    depends_on:
      - server
